#pragma config(Sensor, port2,  rightlight,     sensorVexIQ_LED)
#pragma config(Sensor, port6,  topbutton,      sensorVexIQ_Touch)
#pragma config(Sensor, port12, leftlight,      sensorVexIQ_LED)
#pragma config(Motor,  motor1,          left,          tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor7,          right,         tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float leftStick;
float rightStick;

float leftFinal;
float rightFinal;

task main(){
	while(true){
		if(true){
			if(getBumperValue(topbutton) == 1){
				setTouchLEDBlinkTime(leftlight,5, 5);
				setTouchLEDBrightness(leftlight, 100);
				setTouchLEDColor(leftlight, colorRed);
				setTouchLEDBlinkTime(rightlight,5, 5);
				setTouchLEDBrightness(rightlight, 100);
				setTouchLEDColor(rightlight, colorRed);
			}

			rightStick = vexRT[ChA] * vexRT[ChA];
			leftStick = vexRT[ChD] * vexRT[ChD];

			leftFinal = leftStick / 100;
			rightFinal = rightStick / 100;

			if(vexRT(ChD) < 0){
				leftFinal = leftFinal * -1;
				setTouchLEDColor(leftlight, colorRed);
				setTouchLEDBrightness(leftlight, 100);
				setTouchLEDBlinkTime(leftlight, 10, 5);
			}
			else if(vexRT(ChD) > 0){
				setTouchLEDColor(leftlight, colorGreen);
				setTouchLEDBrightness(leftlight, 100);
			}
			else{
				setTouchLEDBrightness(leftlight, 0);
				setTouchLEDBlinkTime(leftlight, 0, 0);
			}
			if(vexRT(ChA) < 0){
				rightFinal = rightFinal * -1;
				setTouchLEDColor(rightlight, colorRed);
				setTouchLEDBrightness(rightlight, 100);
				setTouchLEDBlinkTime(rightlight, 10, 5);
			}
			else if(vexRT(ChA) > 0){
				setTouchLEDColor(rightlight, colorGreen);
				setTouchLEDBrightness(rightlight, 100);
			}
			else{
				setTouchLEDBrightness(rightlight, 0);
				setTouchLEDBlinkTime(rightlight, 0, 0);
			}
		}
		setMotorSpeed(left, leftFinal);
		setMotorSpeed(right,rightFinal);
	}
}
